config/routes.rb
Tugas4::Application.routes.draw do
  devise_for :users
  resources :tosmics do
    member do
      put "like", to: "tosmics#upvote"
    end
  end
  
  root "tosmics#index"
end

app/models/tosmic.rb
class Tosmic < ActiveRecord::Base
  acts_as_votable
  belongs_to :user

  has_attached_file :image, :styles => { :medium => "200x100^"  },
                    :url => "/image/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/image/:id/:style/:basename.:extension"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :image, :less_than => 200.kilobytes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tosmics  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tosmics_controller.rb
class TosmicsController < ApplicationController
  before_action :find_tosmic, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @tosmics = Tosmic.all.order("created_at DESC")
  end

  def show
    
  end

  def new
    @tosmic = current_user.tosmics.build
  end

  def create
    @tosmic = current_user.tosmics.build(tosmic_params)

    if @tosmic.save
      redirect_to @tosmic, notice: "Sukses Menyimpan"
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    if @tosmic.update(tosmic_params)
      redirect_to @tosmic, notice: "Update Sukses"
    else
      render 'edit'
    end
  end

  def destroy
    @tosmic.destroy
    redirect_to root_path       
  end

  def upvote
    @tosmic.upvote_by current_user
    redirect_to :back
  end

  def tosmic_params
    params.require(:tosmic).permit(:title, :image)
  end   

  def find_tosmic
    @tosmic = Tosmic.find(params[:id])
  end
end

app/controllers/tosmics_controller1.rb
class TosmicsController < ApplicationController
  before_action :find_tosmic, only: [:show, :edit, :update, :destroy]
  
  def index
    @tosmics = Tosmic.all.order("created_at DESC")
  end

  def show
    @tosmic = Tosmic.new
  end
 
  def new
  end

  def create
    @tosmic = Tosmic.new(tosmic_params)

    if @tosmic.save
      redirect_to @tosmic, notice: "Sukses Menyimpan"

    else
      render 'new'
    end
  end

  def update
  end

  def destroy
  end

  private

  def tosmic_params
    params.require(:tosmic).permit(:title)
  end

  def find_tosmic
    @tosmic = Tosmic.find(params[:id])
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tosmics_helper.rb
module TosmicsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Tugas 4
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
  = csrf_meta_tags 
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Tosmic Project", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New File", new_tosmic_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"

    = yield

app/views/tosmics/_form.html.haml
= simple_form_for @tosmic, html: { multipart: true } do |f|
  - if @tosmic.errors.any?
    #errors
    %h2
    = pluralize(@tosmic.errors.count, "error")
    prevented this from saving
    %ul
      - @tosmic.errors.full_messages.each do |msg|
        %li = msg

  .form-group
    = f.input :title, input_html: {class: 'form-control'}

  .form-group
    = f.label :image, class: "control-label"
    = f.file_field :image, input_html: {class: 'form-control'}

  = f.button :submit, class: "btn btn-primary"

  

app/views/tosmics/create.html.haml
<h1>Tosmics#create</h1>
<p>Find me in app/views/tosmics/create.html.erb</p>

app/views/tosmics/destroy.html.haml
<h1>Tosmics#destroy</h1>
<p>Find me in app/views/tosmics/destroy.html.erb</p>

app/views/tosmics/edit.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit File
      .panel-body
        %strong.center Current Image
        %br
        = image_tag @tosmic.image.url(:medium)
        %br
        = render 'form'

app/views/tosmics/index.html.haml
#tosmics.transitions-enabled
- @tosmics.each do |tosmic|
  .box.panel.panel-default
    = link_to (image_tag tosmic.image.url(:medium)), tosmic
    .panel-body
      %h2= link_to tosmic.title, tosmic
      %p.user
      Submitted by
      = tosmic.user.email

app/views/tosmics/new.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 Upload Image
      .panel-body
        = render 'form'

app/views/tosmics/show.html.haml
#tosmic_show.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.tosmic_image
        = image_tag @tosmic.image.url(:medium)
      .panel-body
        %h1= @tosmic.title
        %p
        Submitted by
        = @tosmic.user.email
      .panel-footer
        .row
          .col-md-6
          .col-md-6
            .btn-group.pull-right
              = link_to like_tosmic_path(@tosmic), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-heart
                  = @tosmic.get_upvotes.size
              - if user_signed_in?
                = link_to "Edit", edit_tosmic_path, class: "btn btn-default"
                = link_to "Delete", tosmic_path, method: :delete, data: { confirm: "Anda Yakin Ingin Menghapus?"}, class: "btn btn-default"

app/views/tosmics/update.html.haml
<h1>Tosmics#update</h1>
<p>Find me in app/views/tosmics/update.html.erb</p>